export const SAMPLE_FILE_NAME = 'Test-Bank-Statement.csv'

export const SAMPLE_TRANSACTIONS = [
  { Amount: '2284.88', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'AAA Debit(s)', 'Transaction Reference': 'CC0001', 'Transaction Detail': 'Test01', 'Bank Reference': 'Bank Reference 01' },
  { Amount: '64646.44', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0002', 'Transaction Detail': 'Test02', 'Bank Reference': 'Bank Reference 02' },
  { Amount: '46592.62', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231215', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0003', 'Transaction Detail': 'Test03', 'Bank Reference': 'Bank Reference 03' },
  { Amount: '86806.96', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231215', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0004', 'Transaction Detail': 'Test04', 'Bank Reference': 'Bank Reference 04' },
  { Amount: '313964.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231216', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0005', 'Transaction Detail': 'Test05', 'Bank Reference': 'Bank Reference 05' },
  { Amount: '162855.24', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231217', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0006', 'Transaction Detail': 'Test06', 'Bank Reference': 'Bank Reference 06' },
  { Amount: '193848.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231218', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0007', 'Transaction Detail': 'Test07', 'Bank Reference': 'Bank Reference 07' },
  { Amount: '200334.16', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231219', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0008', 'Transaction Detail': 'Test08', 'Bank Reference': 'Bank Reference 08' },
  { Amount: '539913.78', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231220', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0009', 'Transaction Detail': 'Test09', 'Bank Reference': 'Bank Reference 09' },
  { Amount: '33285.16', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231221', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0010', 'Transaction Detail': 'Test10', 'Bank Reference': 'Bank Reference 10' },
  { Amount: '36088.44', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231222', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0011', 'Transaction Detail': 'Test11', 'Bank Reference': 'Bank Reference 11' },
  { Amount: '40378', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231223', 'Transaction Description': 'AAA Debit(s)', 'Transaction Reference': 'CC0012', 'Transaction Detail': 'Test12', 'Bank Reference': 'Bank Reference 12' },
  { Amount: '217323.4', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231224', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0013', 'Transaction Detail': 'Test13', 'Bank Reference': 'Bank Reference 13' },
  { Amount: '29844', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231225', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0014', 'Transaction Detail': 'Test14', 'Bank Reference': 'Bank Reference 14' },
  { Amount: '60343.24', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231226', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0015', 'Transaction Detail': 'Test15', 'Bank Reference': 'Bank Reference 15' },
  { Amount: '68743.68', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231227', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0016', 'Transaction Detail': 'Test16', 'Bank Reference': 'Bank Reference 16' },
  { Amount: '87113.64', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231228', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0017', 'Transaction Detail': 'Test17', 'Bank Reference': 'Bank Reference 17' },
  { Amount: '13757.5', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0018', 'Transaction Detail': 'Test18', 'Bank Reference': 'Bank Reference 18' },
  { Amount: '39906.28', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0019', 'Transaction Detail': 'Test19', 'Bank Reference': 'Bank Reference 19' },
  { Amount: '58039.76', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0020', 'Transaction Detail': 'Test20', 'Bank Reference': 'Bank Reference 20' },
  { Amount: '59937.66', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0021', 'Transaction Detail': 'Test21', 'Bank Reference': 'Bank Reference 21' },
  { Amount: '604.92', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0022', 'Transaction Detail': 'Test22', 'Bank Reference': 'Bank Reference 22' },
  { Amount: '131867.3', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0023', 'Transaction Detail': 'Test23', 'Bank Reference': 'Bank Reference 23' },
  { Amount: '158041.82', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0024', 'Transaction Detail': 'Test24', 'Bank Reference': 'Bank Reference 24' },
  { Amount: '264873', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0025', 'Transaction Detail': 'Test25', 'Bank Reference': 'Bank Reference 25' },
  { Amount: '51028.9', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0026', 'Transaction Detail': 'Test26', 'Bank Reference': 'Bank Reference 26' },
  { Amount: '52799.04', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0027', 'Transaction Detail': 'Test27', 'Bank Reference': 'Bank Reference 27' },
  { Amount: '141040.7', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0028', 'Transaction Detail': 'Test28', 'Bank Reference': 'Bank Reference 28' },
  { Amount: '25179.42', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0029', 'Transaction Detail': 'Test29', 'Bank Reference': 'Bank Reference 29' },
  { Amount: '369839.26', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0030', 'Transaction Detail': 'Test30', 'Bank Reference': 'Bank Reference 30' },
  { Amount: '414268.52', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0031', 'Transaction Detail': 'Test31', 'Bank Reference': 'Bank Reference 31' },
  { Amount: '249.4', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Outgoing FX Transfer(s)', 'Transaction Reference': 'CC0032', 'Transaction Detail': 'Test32', 'Bank Reference': 'Bank Reference 32' },
  { Amount: '1050', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': 'CC0033', 'Transaction Detail': 'Test33', 'Bank Reference': 'Bank Reference 33' },
  { Amount: '2903.3', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': 'CC0034', 'Transaction Detail': 'Test34', 'Bank Reference': 'Bank Reference 34' },
  { Amount: '10425.68', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0035', 'Transaction Detail': 'Test35', 'Bank Reference': 'Bank Reference 35' },
  { Amount: '11532.8', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': 'CC0036', 'Transaction Detail': 'Test36', 'Bank Reference': 'Bank Reference 36' },
  { Amount: '11803.6', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': 'CC0037', 'Transaction Detail': 'Test37', 'Bank Reference': 'Bank Reference 37' },
  { Amount: '40764.38', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': 'CC0038', 'Transaction Detail': 'Test38', 'Bank Reference': 'Bank Reference 38' },
  { Amount: '45011.72', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0039', 'Transaction Detail': 'Test39', 'Bank Reference': 'Bank Reference 39' },
  { Amount: '64411.62', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Outgoing FX Transfer(s)', 'Transaction Reference': 'CC0040', 'Transaction Detail': 'Test40', 'Bank Reference': 'Bank Reference 40' },
  { Amount: '66309.52', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0041', 'Transaction Detail': 'Test41', 'Bank Reference': 'Bank Reference 41' },
  { Amount: '95725.2', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0042', 'Transaction Detail': 'Test42', 'Bank Reference': 'Bank Reference 42' },
  { Amount: '122001.44', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': 'CC0043', 'Transaction Detail': 'Test43', 'Bank Reference': 'Bank Reference 43' },
  { Amount: '270202', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Outgoing Transfer(s)', 'Transaction Reference': 'CC0044', 'Transaction Detail': 'Test44', 'Bank Reference': 'Bank Reference 44' },
  { Amount: '10839.38', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0046', 'Transaction Detail': 'Test46', 'Bank Reference': 'Bank Reference 46' },
  { Amount: '32983.42', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0047', 'Transaction Detail': 'Test47', 'Bank Reference': 'Bank Reference 47' },
  { Amount: '34544.36', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0048', 'Transaction Detail': 'Test48', 'Bank Reference': 'Bank Reference 48' },
  { Amount: '4887.68', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0049', 'Transaction Detail': 'Test49', 'Bank Reference': 'Bank Reference 49' },
  { Amount: '95173.42', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0050', 'Transaction Detail': 'Test50', 'Bank Reference': 'Bank Reference 50' },
  { Amount: '115513.38', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0051', 'Transaction Detail': 'Test51', 'Bank Reference': 'Bank Reference 51' },
  { Amount: '141068.74', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0052', 'Transaction Detail': 'Test52', 'Bank Reference': 'Bank Reference 52' },
  { Amount: '422729.98', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0053', 'Transaction Detail': 'Test53', 'Bank Reference': 'Bank Reference 53' },
  { Amount: '52647.96', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0054', 'Transaction Detail': 'Test54', 'Bank Reference': 'Bank Reference 54' },
  { Amount: '59145.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0055', 'Transaction Detail': 'Test55', 'Bank Reference': 'Bank Reference 55' },
  { Amount: '232590.3', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0056', 'Transaction Detail': 'Test56', 'Bank Reference': 'Bank Reference 56' },
  { Amount: '15987.94', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0057', 'Transaction Detail': 'Test57', 'Bank Reference': 'Bank Reference 57' },
  { Amount: '52029.28', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0058', 'Transaction Detail': 'Test58', 'Bank Reference': 'Bank Reference 58' },
  { Amount: '59359.72', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0059', 'Transaction Detail': 'Test59', 'Bank Reference': 'Bank Reference 59' },
  { Amount: '523593.56', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0060', 'Transaction Detail': 'Test60', 'Bank Reference': 'Bank Reference 60' },
  { Amount: '530.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0061', 'Transaction Detail': 'Test61', 'Bank Reference': 'Bank Reference 61' },
  { Amount: '10361', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0062', 'Transaction Detail': 'Test62', 'Bank Reference': 'Bank Reference 62' },
  { Amount: '66161.04', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0063', 'Transaction Detail': 'Test63', 'Bank Reference': 'Bank Reference 63' },
  { Amount: '112725.86', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0064', 'Transaction Detail': 'Test64', 'Bank Reference': 'Bank Reference 64' },
  { Amount: '20633.38', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0065', 'Transaction Detail': 'Test65', 'Bank Reference': 'Bank Reference 65' },
  { Amount: '44263.52', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0066', 'Transaction Detail': 'Test66', 'Bank Reference': 'Bank Reference 66' },
  { Amount: '51840.42', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0067', 'Transaction Detail': 'Test67', 'Bank Reference': 'Bank Reference 67' },
  { Amount: '26605.86', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': 'CC0068', 'Transaction Detail': 'Test68', 'Bank Reference': 'Bank Reference 68' },
  { Amount: '26873.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Outgoing FX Transfer(s)', 'Transaction Reference': 'CC0069', 'Transaction Detail': 'Test69', 'Bank Reference': 'Bank Reference 69' },
  { Amount: '46600', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Outgoing Transfer(s)', 'Transaction Reference': 'CC0070', 'Transaction Detail': 'Test70', 'Bank Reference': 'Bank Reference 70' },
  { Amount: '177000.6', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0071', 'Transaction Detail': 'Test71', 'Bank Reference': 'Bank Reference 71' },
  { Amount: '244684.56', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': 'CC0072', 'Transaction Detail': 'Test72', 'Bank Reference': 'Bank Reference 72' },
  { Amount: '19730.98', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'AAA Debit(s)', 'Transaction Reference': 'CC0073', 'Transaction Detail': 'Test73', 'Bank Reference': 'Bank Reference 73' },
  { Amount: '20067.36', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'AAA Debit(s)', 'Transaction Reference': 'CC0008504895', 'Transaction Detail': 'Test74', 'Bank Reference': 'Bank Reference 74' },
  { Amount: '36992.86', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test75', 'Bank Reference': 'Bank Reference 75' },
  { Amount: '50803.46', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test76', 'Bank Reference': 'Bank Reference 76' },
  { Amount: '81435.66', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test77', 'Bank Reference': 'Bank Reference 77' },
  { Amount: '4888.94', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test78', 'Bank Reference': 'Bank Reference 78' },
  { Amount: '8750.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test79', 'Bank Reference': 'Bank Reference 79' },
  { Amount: '25257.38', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test80', 'Bank Reference': 'Bank Reference 80' },
  { Amount: '35422.46', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test81', 'Bank Reference': 'Bank Reference 81' },
  { Amount: '48786.78', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test82', 'Bank Reference': 'Bank Reference 82' },
  { Amount: '154498', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test83', 'Bank Reference': 'Bank Reference 83' },
  { Amount: '26984.64', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test84', 'Bank Reference': 'Bank Reference 84' },
  { Amount: '37688.18', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test85', 'Bank Reference': 'Bank Reference 85' },
  { Amount: '49108.56', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test86', 'Bank Reference': 'Bank Reference 86' },
  { Amount: '5100', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test87', 'Bank Reference': 'Bank Reference 87' },
  { Amount: '10350', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test88', 'Bank Reference': 'Bank Reference 88' },
  { Amount: '17160', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'Customer Outgoing Fedwire(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test89', 'Bank Reference': 'Bank Reference 89' },
  { Amount: '25810.94', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Debit', Date: '20231214', 'Transaction Description': 'BBB Balance Debit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test90', 'Bank Reference': 'Bank Reference 90' },
  { Amount: '26565.92', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test91', 'Bank Reference': 'Bank Reference 91' },
  { Amount: '26575.56', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test92', 'Bank Reference': 'Bank Reference 92' },
  { Amount: '108443.1', Currency: 'USD', 'Account Name': 'World Wide Bank', 'Account Number': 'SAVINGS', 'Credit or Debit': 'Credit', Date: '20231214', 'Transaction Description': 'BBB Balance Credit(s)', 'Transaction Reference': '', 'Transaction Detail': 'Test93', 'Bank Reference': 'Bank Reference 93' },
]

export const SAMPLE_REPORT_MERCHANT = {
  transactions_analysed: 92,
  confidence_score: 89,
  leakage_patterns: [
    {
      pattern_name: 'Fedwire Overuse on Sub-$50K Transfers',
      category: 'Fee Optimisation',
      severity: 'Critical',
      priority: 'Immediate',
      description: '12 Customer Outgoing Fedwire transactions totalling $390,803 — including 9 transfers under $50,000 — are being sent via premium wire when free ACH or Same-Day ACH would suffice. At $35/wire, fee waste is compounding daily.',
      evidence: 'Fedwires identified: CC0033 ($1,050), CC0034 ($2,903), CC0036 ($11,533), CC0037 ($11,804), CC0038 ($40,764), Test78 ($4,889), Test79 ($8,750), Test83 ($154,498), Test87 ($5,100), Test88 ($10,350), Test89 ($17,160), CC0043 ($122,001). 9 of 12 are below $50K threshold where ACH is optimal.',
      estimated_annual_loss: 72800,
      estimated_recovery_amount: 58200,
      actionable_fix: 'Route all domestic transfers under $50,000 via Same-Day ACH (free or $0.25–$1 per transaction). Reserve Fedwire only for same-day settlements above $100,000 where timing is critical.',
      implementation_steps: [
        'Audit all Fedwire recipients — identify which accept ACH (most domestic banks do)',
        'Update payment instructions for sub-$50K recurring payees to ACH routing',
        'Set a bank policy: auto-escalate to Fedwire only for amounts >$100K or same-day critical',
      ],
      timeline: '1–2 weeks',
      effort: 'Low',
    },
    {
      pattern_name: 'Unoptimised FX Transfer Spread',
      category: 'Fee Optimisation',
      severity: 'High',
      priority: 'Immediate',
      description: '3 Outgoing FX Transfer transactions totalling $91,534 show no evidence of rate negotiation or use of specialist FX providers. World Wide Bank\'s typical 2–3% spread costs significantly more than specialist rates of 0.3–0.5%.',
      evidence: 'CC0032 ($249), CC0040 ($64,412), CC0069 ($26,873) — all on Dec 14. Implicit FX cost at 2.5% spread: ~$2,288 on this batch alone. Annualised over similar monthly frequency: ~$27,500/year in spread overpayment.',
      estimated_annual_loss: 44200,
      estimated_recovery_amount: 36800,
      actionable_fix: 'Open a Wise Business or Airwallex account for all international FX transfers. Mid-market rates with sub-0.5% fees eliminate the 2–3% bank spread immediately.',
      implementation_steps: [
        'Open Wise Business account (free, same-day setup)',
        'Fund via local bank transfer and initiate FX transfers at mid-market rate',
        'Compare rate on each transfer — document savings vs previous bank rate',
      ],
      timeline: '2–3 days',
      effort: 'Low',
    },
    {
      pattern_name: 'Dec 14 Settlement Concentration Risk',
      category: 'Settlement',
      severity: 'High',
      priority: 'Short-term',
      description: '58 of 92 transactions — including the 5 largest debits — are clustered on Dec 14, creating a $1.9M debit vs $1.5M credit imbalance. This daily cash gap generates overdraft risk and missed float income on idle balances.',
      evidence: 'Dec 14 top debits: CC0060 ($523,594), CC0053 ($422,730), CC0031 ($414,269), CC0056 ($232,590). Largest credit: CC0030 ($369,839). Net Dec 14 shortfall: ~$400K. CC0044 ($270,202 Outgoing Transfer) and CC0044 add further unhedged outflows.',
      estimated_annual_loss: 38400,
      estimated_recovery_amount: 29600,
      actionable_fix: 'Stagger large outgoing payments across the week. Implement a treasury rule: outgoing transfers >$100K require a confirmed inbound settlement within 24 hours or a pre-funded reserve.',
      implementation_steps: [
        'Map all recurring large debit dates and shift non-time-critical ones to T+1 or T+2',
        'Request World Wide Bank\'s sweep account product to earn interest on overnight float',
        'Set a daily net-position alert: notify treasury if outflows exceed inflows by >$200K',
      ],
      timeline: '2–4 weeks',
      effort: 'Medium',
    },
  ],
  quick_wins: [
    'Switch the 9 sub-$50K Fedwires to Same-Day ACH immediately — saves ~$315/batch in wire fees',
    'Open Wise Business today and route your next FX transfer through it to capture mid-market rate',
    'Enable daily net-position SMS alerts from World Wide Bank to catch Dec 14-style cash gaps early',
  ],
}

export const SAMPLE_REPORT_INDIVIDUAL = {
  transactions_analysed: 92,
  confidence_score: 84,
  leakage_patterns: [
    {
      pattern_name: 'Wire Transfer Fees on Unnecessary Payments',
      category: 'Fee Optimisation',
      severity: 'High',
      priority: 'Immediate',
      description: '12 Customer Outgoing Fedwire transfers totalling $390,803 include multiple small payments ($1,050–$17,160) that carry $25–$45 bank fees each when Zelle, ACH, or a free app transfer would cost nothing.',
      evidence: 'Fedwires: CC0033 ($1,050), CC0034 ($2,903), CC0036 ($11,533), CC0037 ($11,804), CC0038 ($40,764), Test78 ($4,889), Test79 ($8,750). At $35/wire × 12 wires/period: estimated $420/period in avoidable fees.',
      estimated_annual_loss: 10920,
      estimated_recovery_amount: 9100,
      actionable_fix: 'Replace domestic wire transfers with Zelle (free, instant) or ACH (free, 1–2 day). Wire only when the recipient explicitly requires it and the amount exceeds $50,000.',
      implementation_steps: [
        'List all Fedwire recipients — check if they have Zelle or accept ACH',
        'Update payment details for eligible contacts in World Wide Bank online banking',
        'Set a personal rule: use wire only for amounts >$50K or international',
      ],
      timeline: '1 week',
      effort: 'Low',
    },
    {
      pattern_name: 'FX Transfer Cost Overrun',
      category: 'Fee Optimisation',
      severity: 'Critical',
      priority: 'Immediate',
      description: '3 international FX transfers totalling $91,534 in a single period suggest regular international payment activity at bank spread rates of 2–3%, when specialist apps offer the mid-market rate at under 0.5% fee.',
      evidence: 'CC0032 ($249), CC0040 ($64,412), CC0069 ($26,873) — all Dec 14. Bank spread at 2.5%: ~$2,288 implicit cost on this batch. At monthly frequency, annual FX cost: ~$27,500 vs ~$4,600 with a specialist = $22,900 overpay.',
      estimated_annual_loss: 27480,
      estimated_recovery_amount: 22900,
      actionable_fix: 'Use Wise or Revolut for all international transfers. Both offer mid-market exchange rates with transparent low fees — typically 0.3–0.5% vs 2–3% at traditional banks.',
      implementation_steps: [
        'Download Wise app and complete KYC (takes ~10 minutes)',
        'Fund via bank transfer and send your next FX payment through Wise',
        'Compare rates before each transfer: use Wise\'s rate calculator vs your bank\'s quote',
      ],
      timeline: '1–2 days',
      effort: 'Low',
    },
    {
      pattern_name: 'Large Unplanned Debit Spikes — Cash Flow Gap',
      category: 'Other',
      severity: 'Medium',
      priority: 'Short-term',
      description: 'Debits of $523,594 and $539,914 appear on Dec 14 and Dec 20 with no obvious corresponding inflows — suggesting large irregular outflows that may not align with a planned personal budget or cash flow cycle.',
      evidence: 'CC0060 ($523,594 debit, Dec 14) and CC0009 ($539,914 debit, Dec 20) are the two largest transactions. Combined $1.06M in 6 days with no matching credit of similar scale. Potential overdraft or emergency fund erosion risk.',
      estimated_annual_loss: 8400,
      estimated_recovery_amount: 5600,
      actionable_fix: 'Set up real-time alerts for all debits above $5,000. Review these two large transactions to confirm they are planned (e.g., property, investment). If not, build a 3-month emergency buffer to prevent distress selling.',
      implementation_steps: [
        'Enable large-debit SMS/push alerts in World Wide Bank mobile app',
        'Categorise CC0060 and CC0009 in your personal budget spreadsheet',
        'If unplanned, set aside an emergency fund equal to 3× your largest monthly debit',
      ],
      timeline: '1–2 weeks',
      effort: 'Low',
    },
  ],
  quick_wins: [
    'Switch your next domestic wire payment to Zelle — saves $35 instantly at zero effort',
    'Open Wise today and route your next international transfer through it to save ~2% on FX',
    'Enable large-transaction push alerts in your banking app to prevent surprise overdrafts',
  ],
}
